=== charan-og67/Smart-Water-Monitoring-and-Conservation-Network/water-data.dtd
<!ELEMENT smartWater (stations, measurements, alerts)>
<!ELEMENT stations (station*)>
<!ELEMENT station (name, location)>
<!ATTLIST station id ID #REQUIRED>
<!ELEMENT name (#PCDATA)>
<!ELEMENT location (#PCDATA)>
<!ELEMENT measurements (measurement*)>
<!ELEMENT measurement (ph, turbidity, temperature)>
<!ATTLIST measurement id ID #REQUIRED stationId IDREF #REQUIRED>
<!ELEMENT ph (#PCDATA)>
<!ELEMENT turbidity (#PCDATA)>
<!ELEMENT temperature (#PCDATA)>
<!ELEMENT alerts (alert*)>
<!ELEMENT alert (severity, message)>
<!ATTLIST alert id ID #REQUIRED stationId IDREF #REQUIRED>
<!ELEMENT severity (#PCDATA)>
<!ELEMENT message (#PCDATA)>

=== charan-og67/Smart-Water-Monitoring-and-Conservation-Network/water-data.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE smartWater SYSTEM "water-data.dtd">
<smartWater>
  <stations><station id="ST-001"><name>Lake View Station</name><location>Hyderabad</location></station></stations>
  <measurements><measurement id="M-001" stationId="ST-001"><ph>7.2</ph><turbidity>2.1</turbidity><temperature>25.4</temperature></measurement></measurements>
  <alerts><alert id="A-001" stationId="ST-001"><severity>Medium</severity><message>Elevated turbidity</message></alert></alerts>
</smartWater>
